color0 #dbe4e4
color1 #ba1a1a
color2 #004041
color3 #4d6262
color4 #403159
color5 #427c7e
color6 #627778
color7 #191c1c
color8 #707979
color9 #ba1a1a
color10 #004041
color11 #4d6262
color12 #403159
color13 #427c7e
color14 #627778
color15 #191c1c

cursor                #191c1c
cursor_text_color     #f8faf9
background            #f8faf9
foreground            #191c1c
selection_foreground  #3f4848
selection_background  #dbe4e4
active_border_color   #004041
inactive_border_color #dbe4e4
url_color             #004041

active_tab_foreground   #ffffff
active_tab_background   #004041
inactive_tab_foreground #3f4848
inactive_tab_background #dbe4e4
cursor_trail_color      #3f4848
