color0 #e2e1eb
color1 #ba1a1a
color2 #333c5f
color3 #5b5e6e
color4 #55324f
color5 #6a7198
color6 #707283
color7 #1b1b1e
color8 #76767f
color9 #ba1a1a
color10 #333c5f
color11 #5b5e6e
color12 #55324f
color13 #6a7198
color14 #707283
color15 #1b1b1e

cursor                #1b1b1e
cursor_text_color     #fbf8fc
background            #fbf8fc
foreground            #1b1b1e
selection_foreground  #45464e
selection_background  #e2e1eb
active_border_color   #333c5f
inactive_border_color #e2e1eb
url_color             #333c5f

active_tab_foreground   #ffffff
active_tab_background   #333c5f
inactive_tab_foreground #45464e
inactive_tab_background #e2e1eb
cursor_trail_color      #45464e
