color0 #e6e4c8
color1 #ba1a1a
color2 #626200
color3 #61611f
color4 #506600
color5 #787700
color6 #797629
color7 #1c1c11
color8 #797861
color9 #ba1a1a
color10 #626200
color11 #61611f
color12 #506600
color13 #787700
color14 #797629
color15 #1c1c11

cursor                #1c1c11
cursor_text_color     #fdfae7
background            #fdfae7
foreground            #1c1c11
selection_foreground  #484833
selection_background  #e6e4c8
active_border_color   #626200
inactive_border_color #e6e4c8
url_color             #626200

active_tab_foreground   #ffffff
active_tab_background   #626200
inactive_tab_foreground #484833
inactive_tab_background #e6e4c8
cursor_trail_color      #484833
